if has("gui_macvim")
	" Alt-] = open definition of current term in vertical split
	map <D-]> :vsp <CR>:exec("tag ".expand("<cword>"))<CR>

	macmenu &File.Print key=<nop>
	map <D-p> :CtrlP<CR>

	" Mouse clicks can sometimes cause my particular MacVim setup to hang.
	noremap <LeftMouse> <nop>
endif

set guifont=Menlo\ for\ Powerline:h12
set guioptions-=r " No right-hand scrollbar
set transparency=15
