if has("gui_macvim")
  " Alt-] = open definition of current term in vertical split
  map <D-]> :vsp <CR>:exec("tag ".expand("<cword>"))<CR>

  macmenu &File.Print key=<nop>
  map <D-p> :CommandT<CR>

  " Close all except the current buffer
  macmenu &File.Close\ Window key=<nop>
  map <D-W> :tabnew <CR>:tabo <CR>
endif

set guifont=Menlo\ for\ Powerline:h12
set guioptions-=r " No right-hand scrollbar
set transparency=0

set fullscreen
