alias hs='hg status'
alias hd='hg diff'
alias ha='hg add'
alias hca='hg commit'
alias hl='hg log --no-merges --style ~/dotfiles/hg/map-cmdline.slog | less'
alias hld='hg log --no-merges --style ~/dotfiles/hg/map-cmdline.slog default..tip | less'
alias hco='hg checkout'
alias hpo='hg push'
alias hgr='hg pull --rebase'
alias hgu='hg pull --update'
alias hre='hg revert --no-backup'

