# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set to the name theme to load.
# Look in ~/.oh-my-zsh/themes/
export ZSH_THEME="robbyrussell"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# export DISABLE_AUTO_TITLE="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(rails git)

# Oh My Zsh!
source $ZSH/oh-my-zsh.sh
unsetopt correct_all

# Customize to your needs...
export PATH=~/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/usr/local/git/bin
[[ -s "/Users/janko/.rvm/scripts/rvm" ]] && source "/Users/janko/.rvm/scripts/rvm"  # This loads RVM into a shell session.

export EDITOR='mvim -f'

alias fenix='cd ~/work/fenix/'
alias birdy='cd ~/work/birdy/'

alias be='bundle exec'
alias cap='bundle exec cap'
alias cucumber='bundle exec cucumber'
alias guard='bundle exec guard'
alias rspec='bundle exec rspec'
alias egs='bundle exec evergreen serve'

alias u='git status -bs'
alias d='git diff'
alias a='git add'
alias gl='git log --pretty=compact --graph --color --first-parent @{upstream}..HEAD'
alias glm='git log --pretty=compact --graph --color --first-parent origin/master..HEAD'
alias glp='git log --pretty=compact --graph --color --first-parent origin/production..origin/master'
alias gco='git checkout'
alias gpo='git push origin'
alias master='git checkout master'
alias gro='git rebase @{upstream}'
alias gri='git rebase --interactive --autosquash'
alias gfe='git fetch'
alias publish-branch='git push -u @{upstream}'

alias reset_fenix='rake db:mongoid:drop db:migrate:reset db:test:prepare && rake db:seed import:companies:interesting solr:reset solr:update_app_buckets index --trace'

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
