# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set to the name theme to load.
# Look in ~/.oh-my-zsh/themes/
export ZSH_THEME="agnoster"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# export DISABLE_AUTO_TITLE="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(rails git zsh-syntax-highlighting)

export DEFAULT_USER="janko"

# Oh My Zsh!
source $ZSH/oh-my-zsh.sh
unsetopt correct_all

# Customize to your needs...
export PATH=~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/usr/local/git/bin:$PATH
[[ -s "/Users/janko/.rvm/scripts/rvm" ]] && source "/Users/janko/.rvm/scripts/rvm"  # This loads RVM into a shell session.

export EDITOR='mvim -f'

source ~/dotfiles/zsh/ruby.zsh
source ~/dotfiles/zsh/git.zsh
source ~/dotfiles/zsh/hg.zsh

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
. ~/.zshrc.local
