# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set to the name theme to load.
# Look in ~/.oh-my-zsh/themes/
export ZSH_THEME="robbyrussell"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# export DISABLE_AUTO_TITLE="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(rails git zsh-syntax-highlighting)

alias get_current_desktop_picture="sqlite3 ~/Library/Application\ Support/Dock/desktoppicture.db 'select * from data'"

alias fastlane="bundle exec fastlane"

export DEFAULT_USER="janko.luin"

# Java: Read all files as UTF-8 (still in 2014, the Mac OS X default is "MacRoman"!)
export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8

# Oh My Zsh!
source $ZSH/oh-my-zsh.sh
unsetopt correct_all

export PATH=~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/usr/local/git/bin:$PATH

export EDITOR='nvim'

source ~/dotfiles/zsh/ruby.zsh
source ~/dotfiles/zsh/git.zsh
source ~/dotfiles/zsh/hg.zsh
source ~/dotfiles/zsh/svn.zsh

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
. ~/.zshrc.local

